apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "uptime-monitor.fullname" . }}-config
  labels:
    {{- include "uptime-monitor.labels" . | nindent 4 }}
data:
  services.yaml: |
{{ .Values.servicesYaml | indent 4 }}
