{{- if and .Values.database.url (not .Values.database.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-monitor.dbSecretName" . }}
  labels:
    {{- include "uptime-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.database.url | quote }}
{{- end }}
{{ if .Values.cronSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "uptime-monitor.cronSecretName" . }}
  labels:
    {{- include "uptime-monitor.labels" . | nindent 4 }}
type: Opaque
stringData:
  CRON_SECRET: {{ .Values.cronSecret | quote }}
{{ end }}
