{{- if .Values.worker.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "uptime-monitor.fullname" . }}-worker
  labels:
    {{- include "uptime-monitor.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: worker
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
{{- end }}
