name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  app:
    name: typecheck & build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run typecheck
      - run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: "1"

  infra:
    name: terraform validate & helm lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.5"
      - name: terraform fmt & validate
        working-directory: deploy/terraform
        run: |
          terraform fmt -check -recursive
          terraform init -backend=false
          terraform validate

      - uses: azure/setup-helm@v4
        with:
          version: v3.15.2
      - name: helm lint & template
        run: |
          helm lint deploy/helm/uptime-monitor
          helm template t deploy/helm/uptime-monitor \
            --set database.url=postgres://u:p@h:5432/db \
            --set web.enabled=true \
            --set serviceMonitor.enabled=true > /dev/null
